services:
  slack-ips:
    container_name: slack-ips
    image: dusnm1/slack-ips:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - XDG_CONFIG_HOME=/opt/config
      - XDG_CACHE_HOME=/opt/cache
      - XDG_DATA_HOME=/opt/data
    volumes:
      - "./data:/opt/data"
      - "./config:/opt/config"